<?php
function DNA_menu() {
    $items['DNA'] = array(
        'title' => 'DNA',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('DNA_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['DNA_success'] = array(
        'title' => 'Success',
        'page callback' => 'DNA_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function DNA_form() {
    $form['input'] = array(
        '#title' => 'First strand DNA sequence',
        '#type' => 'textfield',
        '#description' => t('Please input the initial DNA sequence to receive its compliment.'),
        '#element_validate' => array('element_validate_strand'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
}

function element_validate_strand($element) {
    $element_input = strtoupper($element['#value']);
    $input_array = str_split($element_input);
    $accepted = array('A','T','C','G');
    foreach($input_array as $letter){
        if (!(in_array($letter, $accepted))){
            form_error($element, t('Please limit input to the four DNA bases: "A," "T," "C," or "G."'));
        }
    }
}

function sister_strand_find($input) {
    $_SESSION['strand'] = $input;
    $parsed_input = str_split($input);
    $sister_strand_array = array();
    foreach($parsed_input as $base) {
        $upper_base = strtoupper($base);
        if ($upper_base === 'A') {
            array_push($sister_strand_array, 'T');
        } elseif ($upper_base === 'T') {
            array_push($sister_strand_array, 'A');
        } elseif ($upper_base === 'C') {
            array_push($sister_strand_array, 'G');
        } elseif ($upper_base === 'G') {
            array_push($sister_strand_array, 'C');
        }
    }
    $sister_strand = implode('',$sister_strand_array);
    return $sister_strand;
}

function DNA_form_submit($form, &$form_state) {
    $input = $form_state['values']['input'];
    $result = sister_strand_find($input);
    $_SESSION['sister_strand'] = $result;

    $form_state['redirect'] = 'DNA_success';
}

function DNA_success() {
    $strand = $_SESSION['strand'];
    $sister_strand = $_SESSION['sister_strand'];
    return '<p>Originial strand: &nbsp;&nbsp;&nbsp;' . $strand . '<br>Your sister strand: ' . $sister_strand . '</p>';
}
